name = "trusted-setup-dev2"
compatibility_date = "2022-10-18"
main = "dist/index.js"

[site]
bucket = "./build"

[build]
command = "yarn && yarn build:worker && echo '{\"name\": \"trusted-setup\",\"main\":\"index.js\"}' > dist/package.json"
